name: Package

on: pull_request

env:
  shell: bash
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_and_test:
    runs-on: windows-2022
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.Python_REQUIRED_VERSION }}

      - name: Create Build Directory
        run: cmake -E make_directory ./build/

      - name: Configure CMake
        working-directory: ./build
        run: cmake -G "Visual Studio 17 2022" -DBUILD_TYPE=Release ../

      - name: Build
        working-directory: ./build
        run: cmake --build . -j 4 --config Release --target PACKAGE

      - uses: actions/upload-artifact@v4
        with:
          name: "package-windows"
          path: "${{ github.workspace }}/build"

