name: Mac Build

on:
  push

env:
  shell: bash
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-12
            generator: "Unix Makefiles"
            nproc: 3
            build_target: all
          - os: macos-14
            generator: "Unix Makefiles"
            nproc: 3
            build_target: all
          - os: ubuntu-latest
            generator: "Unix Makefiles"
            nproc: 4
            build_target: all
          - os: windows-2019
            generator: "Visual Studio 16 2019"
            nproc: 4
            build_target: ALL_BUILD
          - os: windows-2022
            generator: "Visual Studio 17 2022"
            nproc: 4
            build_target: ALL_BUILD

    steps:
      - uses: actions/checkout@v4

      - name: Create Build Directory
        run: cmake -E make_directory ./build/

      - name: Configure CMake
        working-directory: ./build
        run: cmake -G "${{ matrix.generator }}" -DBUILD_TYPE=Release ../

      - name: Build
        working-directory: ./build
        run: cmake --build . -j ${{ matrix.nproc }} --config Release --target ${{ matrix.build_target }}

      - name: Run Tests
        working-directory: ./build
        run: ctest
